### ISSUE TITLE
chore: Add Cohort page (WEB-51) 

### ISSUE THREAD

**Issue by Dissurender** [dallassoftwaredevelopers/DSDsite#100]
## Task

Issue:
The Cohorts page needs to be built out from its placeholder.

- [x] Write out structure and implements in Cohorts/page.jsx
- [x] Replicate data and formatting from the [Figma "Cohorts" page](https://www.figma.com/design/8cpiqfhzCrzjqK7UOyJKvn/DSD?node-id=706-731&t=dbFuLPQW3ZQm0Rl6-4)
- [x] Placehold videos until links provided

> Steps to contribute. NEVER COMMIT TO MAIN. NEVER COMMIT TO MAIN. It should always be on your own branch and that branch name should match the issue. Ensure that you are addressing the correct issue. Each issue will be listed as something like a chore, fix, bug, etc. Your commit message MUST start with one of these tags that correspond with your issue. Followed by your commit message and your commit message must end with the branch name, for example (WEB-1)
>
> An example commit message would look like this: chore: create contributing guidelines (WEB-8)
>
> Commit messages should not be written in an action or present tense. It also should not mention tasks unrelated to the issue "Creating Contributing Guidelines and will work on next task" is not what we would want to see as a commit message.
>
> After a pull request is approved, the branch should be deleted once merged.

**Comment by Dissurender** [comment]
@GetBlackBoxSolutions While maintaining the style that's in the Figma, the current look for above the fold on the "Cohorts" page looks like this at 1080p on Firefox:
![image](https://github.com/user-attachments/assets/24474f48-5948-4e6f-a780-a639632b089c)

The current style is in line with the "The Community" page.
Do we want to vary the styling on the typography to get all three paragraphs above the fold?

**Comment by Dissurender** [comment]
PR #102
